package actions

import (
	"git.aprentout.com/touslesmemes/api/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Channel)
// DB Table: Plural (channels)
// Resource: Plural (Channels)
// Path: Plural (/channels)
// View Template Folder: Plural (/templates/channels/)

// ChannelsResource is the resource for the Channel model
type ChannelsResource struct {
	buffalo.Resource
}

// List gets all Channels. This function is mapped to the path
// GET /channels
func (v ChannelsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	channels := &models.Channels{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Channels from the DB
	if err := q.All(channels); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.JSON(channels))
}

// Show gets the data for one Channel. This function is mapped to
// the path GET /channels/{channel_id}
func (v ChannelsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Channel
	channel := &models.Channel{}

	// To find the Channel the parameter channel_id is used.
	if err := tx.Find(channel, c.Param("channel_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, channel))
}

// New renders the form for creating a new Channel.
// This function is mapped to the path GET /channels/new
func (v ChannelsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Channel{}))
}

// Create adds a Channel to the DB. This function is mapped to the
// path POST /channels
func (v ChannelsResource) Create(c buffalo.Context) error {
	// Allocate an empty Channel
	channel := &models.Channel{}

	// Bind channel to the html form elements
	if err := c.Bind(channel); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(channel)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, channel))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Channel was created successfully")

	// and redirect to the channels index page
	return c.Render(201, r.Auto(c, channel))
}

// Edit renders a edit form for a Channel. This function is
// mapped to the path GET /channels/{channel_id}/edit
func (v ChannelsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Channel
	channel := &models.Channel{}

	if err := tx.Find(channel, c.Param("channel_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, channel))
}

// Update changes a Channel in the DB. This function is mapped to
// the path PUT /channels/{channel_id}
func (v ChannelsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Channel
	channel := &models.Channel{}

	if err := tx.Find(channel, c.Param("channel_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Channel to the html form elements
	if err := c.Bind(channel); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(channel)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, channel))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Channel was updated successfully")

	// and redirect to the channels index page
	return c.Render(200, r.Auto(c, channel))
}

// Destroy deletes a Channel from the DB. This function is mapped
// to the path DELETE /channels/{channel_id}
func (v ChannelsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Channel
	channel := &models.Channel{}

	// To find the Channel the parameter channel_id is used.
	if err := tx.Find(channel, c.Param("channel_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(channel); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Channel was destroyed successfully")

	// Redirect to the channels index page
	return c.Render(200, r.Auto(c, channel))
}
